Transform: 'AWS::Serverless-2016-10-31'
Resources:

  Trigger_Glue_ETL_Function:
    # This resource creates a Lambda function.
    Type: 'AWS::Serverless::Function'

    Properties:

      # This function uses the python3.6runtime.
      Runtime: python3.6

      # This is the Lambda function's handler.
      Handler: lambda_function.lambda_handler

      # The location of the Lambda function code.
      CodeUri: ./

